<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Tabla de Multiplicar del 7</title>
</head>
<body>
	<h1>TABLA DE MULTIPLICAR DEL 7</h1>
			<table>
			<tr>
				<th>Multiplicando</th>
				<th>Por</th>
				<th>Multiplicador</th>
				<th>Igual a</th>
				<th>valor</th>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>1</td>
				<td>=</td>
				<td>7</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>2</td>
				<td>=</td>
				<td>14</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>3</td>
				<td>=</td>
				<td>21</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>4</td>
				<td>=</td>
				<td>28</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>5</td>
				<td>=</td>
				<td>35</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>6</td>
				<td>=</td>
				<td>42</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>7</td>
				<td>=</td>
				<td>49</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>8</td>
				<td>=</td>
				<td>56</td>
			</tr>
			<tr>
				<td>7</td>
				<td>*</td>
				<td>9</td>
				<td>=</td>
				<td>63</td>
			</tr>
		</table>
</body>
</html>